version: "3.9"
services:
  php:
    build:
      args:
        user: default_user
        uid: 1000
      context: ./docker/php
      dockerfile: php.dockerfile
    image: devellopah/php
    container_name: php-ip-geo-locator
    tty: true
    restart: always
    working_dir: /var/www/IP_Geo_Locator
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./:/var/www/IP_Geo_Locator
    networks:
      - geoLocatorIp-network
  nginx:
    container_name: nginx-ip-geo-locator
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - geoLocatorIp-network
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ./:/var/www/IP_Geo_Locator
      - ./docker/nginx/conf.d:/etc/nginx/cond.d
      - ./docker/nginx/log:/var/log/nginx/

networks:
  geoLocatorIp-network:
    driver: bridge

